name: Google drive Tests
on:
  workflow_dispatch:

jobs:
  command-test:
    name: Testing the command generation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: Generate build command
        uses: ./
        with:
          enginePath: 'C:/Program Files/Epic Games/UE_5.4'
          uprojectPath: '${{github.workspace}}/Test/ViridianCo.uproject'
          builConfig: "Shipping"
          platform: "Win64"
          clean: true
          cook: true
          stage: true
          package: true
          pak: true
          server: false
          archive: true
          archivePath: "${{github.workspace}}/Archive"
          nullrhi: true
          editor: false
          ecriptIniFiles: true
          release: false
          patch: false
          deletePDB: false
          anticheatEnabled: false
          anticheatPrivateKey: "private key"
          anticheatPublicCert: "cert"
          maps: false

     


